yenxo: Variant conversion
Variant conversion
Opt-in type traits
Variant conversion for user defined struct-like types
Modules
Policy
The traits' settings.
Meta
Metadata that might be used by the traits.
Classes
struct yenxo::trait::Var< Derived, Policy >
Adds conversion support to and from Variant
struct yenxo::trait::UpdateFromVar< Derived, Policy >
Adds member void updateVar(Variant const&)
struct yenxo::trait::UpdateFromOpt< Derived, Opt >
Adds member void updateOpt(Opt const&)
Macros
#define YENXO_TO_VARIANT(T)
Enables to yenxo::Variant conversion for T
#define YENXO_TO_VARIANT_P(T, Policy)
Enables to yenxo::Variant conversion for T
#define YENXO_FROM_VARIANT(T)
Enables from yenxo::Variant conversion for T
#define YENXO_FROM_VARIANT_P(T, Policy)
Enables from yenxo::Variant conversion for T
#define YENXO_UPDATE_FROM_VARIANT(T)
Enables from yenxo::Variant update for T
#define YENXO_UPDATE_FROM_VARIANT_P(T, Policy)
Enables from yenxo::Variant update for T
#define YENXO_UPDATE_FROM_OPT(T, Opt)
Enables from Opt update for T
Functions
template<class T , class Policy = VarPolicy>
Variant yenxo::trait::toVariantImpl (T const &x)
Convert x to Variant
template<class T , class Policy = VarPolicy>
T yenxo::trait::fromVariantImpl (yenxo::Variant const &x)
Convert x to T
template<class T , class Policy = VarPolicy>
void yenxo::trait::updateVarImpl (T &self, Variant const &x)
Updates the specified fields.
template<class T , class Opt >
void yenxo::trait::updateOptImpl (T &self, Opt const &x)
Updates the specified fields.
Detailed Description
Variant conversion for user defined struct-like types
Macro Definition Documentation
YENXO_TO_VARIANT
#define YENXO_TO_VARIANT (T)
#include <yenxo/variant_traits.hpp>
Value:
    static yenxo::Variant toVariant(T const& x) {                                        \
        return yenxo::trait::toVariantImpl<T>(x);                                        \
    }
Enables to yenxo::Variant conversion for T
T can provide
names();
defaults().
Precondition
T should be a Boost.Hana.Struct.
YENXO_TO_VARIANT_P
#define YENXO_TO_VARIANT_P (T, Policy)
#include <yenxo/variant_traits.hpp>
Value:
    static yenxo::Variant toVariant(T const& x) {                                        \
        return yenxo::trait::toVariantImpl<T, Policy>(x);                                \
    }
Enables to yenxo::Variant conversion for T
Conversion can be customized via Policy.
T can provide
names();
defaults().
Precondition
T should be a Boost.Hana.Struct.
YENXO_FROM_VARIANT
#define YENXO_FROM_VARIANT (T)
#include <yenxo/variant_traits.hpp>
Value:
    static T fromVariant(yenxo::Variant const& x) {                                      \
        return yenxo::trait::fromVariantImpl<T>(x);                                      \
    }
Enables from yenxo::Variant conversion for T
T can provide
names();
defaults().
Precondition
T should be a Boost.Hana.Struct.
YENXO_FROM_VARIANT_P
#define YENXO_FROM_VARIANT_P (T, Policy)
#include <yenxo/variant_traits.hpp>
Value:
    static T fromVariant(yenxo::Variant const& x) {                                      \
        return yenxo::trait::fromVariantImpl<T, Policy>(x);                              \
    }
Enables from yenxo::Variant conversion for T
Conversion can be customized via Policy.
T can provide
names();
defaults().
Precondition
T should be a Boost.Hana.Struct.
YENXO_UPDATE_FROM_VARIANT
#define YENXO_UPDATE_FROM_VARIANT (T)
#include <yenxo/variant_traits.hpp>
Value:
    void updateVar(yenxo::Variant const& x) {                                            \
        yenxo::trait::updateVarImpl<T>(*this, x);                                        \
    }
Enables from yenxo::Variant update for T
T can provide
names().
Precondition
T should be a Boost.Hana.Struct.
YENXO_UPDATE_FROM_VARIANT_P
#define YENXO_UPDATE_FROM_VARIANT_P (T, Policy)
#include <yenxo/variant_traits.hpp>
Value:
    void updateVar(yenxo::Variant const& x) {                                            \
        yenxo::trait::updateVarImpl<T, Policy>(*this, x);                                \
    }
Enables from yenxo::Variant update for T
Updating can be customized via Policy.
T can provide
names().
Precondition
T should be a Boost.Hana.Struct.
YENXO_UPDATE_FROM_OPT
#define YENXO_UPDATE_FROM_OPT (T, Opt)
#include <yenxo/variant_traits.hpp>
Value:
    void updateOpt(Opt const& x) {                                                       \
        yenxo::trait::updateOptImpl(*this, x);                                           \
    }
Enables from Opt update for T
Precondition
T should be a Boost.Hana.Struct.
Function Documentation
toVariantImpl()
template<class T , class Policy = VarPolicy> Variant yenxo::trait::toVariantImpl (T const & x)
#include <yenxo/variant_traits.hpp>
Convert x to Variant
Conversion can be customized via Policy.
T can provide
names();
defaults().
Precondition
T should be a Boost.Hana.Struct.
References yenxo::isContainer(), and yenxo::isOptional().
fromVariantImpl()
template<class T , class Policy = VarPolicy> T yenxo::trait::fromVariantImpl (yenxo::Variant const & x)
#include <yenxo/variant_traits.hpp>
Convert x to T
Conversion can be customized via Policy.
T can provide
names();
defaults().
Precondition
T should be a Boost.Hana.Struct.
References yenxo::isContainer(), yenxo::isOptional(), and yenxo::Variant::map().
updateVarImpl()
template<class T , class Policy = VarPolicy> void yenxo::trait::updateVarImpl (T & self, Variant const & x)
#include <yenxo/variant_traits.hpp>
Updates the specified fields.
Conversion can be customized via Policy.
T can provide
names().
Precondition
T should be a Boost.Hana.Struct.
References yenxo::trait::detail::hasUpdateVar, and yenxo::Variant::map().
updateOptImpl()
template<class T , class Opt > void yenxo::trait::updateOptImpl (T & self, Opt const & x)
#include <yenxo/variant_traits.hpp>
Updates the specified fields.
Precondition
Derived should be a Boost.Hana.Struct.
References yenxo::isOptional().